# Generated by Django 2.2 on 2021-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('summary', models.CharField(max_length=500)),
                ('github_link', models.CharField(max_length=100)),
                ('time_period', models.CharField(max_length=50)),
            ],
        ),
    ]
